"$schema" = 'https://starship.rs/config-schema.json'

add_newline = false
format = """$status$cmd_duration

<$username$hostname$custom> | $directory$git_branch $git_status$git_state
$time $character"""


[character]
success_symbol = '>'
error_symbol = '>'

[git_commit]
tag_symbol = " tag "

[git_status]
ahead = ">"
behind = "<"
diverged = "<>"
renamed = "r"
deleted = "x"

[cmd_duration]
format = "ran for [$duration]($style)"
style = "italic yellow"

[custom.toolbox]
when = """ test -f /run/.containerenv && test -f /run/.toolboxenv """
description = "Config for toolbox"
style = "red"
command = """ cat /run/.containerenv | sed -n '2 p' | awk -F '"' 'NF>2{print $2}' """
format = ':[$output]($style)'

[directory]
read_only = " ro"

[fill]
symbol = ' '

[git_branch]
format = "on [$branch(:$remote_branch)]($style)"

[hg_branch]
symbol = "hg "

[hostname]
ssh_only = false
ssh_symbol = "ssh:"
format = "@[$ssh_symbol$hostname]($style)"

[memory_usage]
symbol = "memory "

[os.symbols]
Alpine = "alp "
Amazon = "amz "
Android = "andr "
Arch = "rch "
CentOS = "cent "
Debian = "deb "
DragonFly = "dfbsd "
Emscripten = "emsc "
EndeavourOS = "ndev "
Fedora = "fed "
FreeBSD = "fbsd "
Garuda = "garu "
Gentoo = "gent "
HardenedBSD = "hbsd "
Illumos = "lum "
Linux = "lnx "
Macos = "mac "
Manjaro = "mjo "
Mariner = "mrn "
MidnightBSD = "mid "
Mint = "mint "
NetBSD = "nbsd "
NixOS = "nix "
OpenBSD = "obsd "
openSUSE = "osuse "
OracleLinux = "orac "
Pop = "pop "
Raspbian = "rasp "
Redhat = "rhl "
RedHatEnterprise = "rhel "
Redox = "redox "
Solus = "sol "
SUSE = "suse "
Ubuntu = "ubnt "
Unknown = "unk "
Windows = "win "

[sudo]
symbol = "#"
disabled = true
format = "[$symbol]($style)"
style = ''

[status]
symbol = '[✗](bold red)'
success_symbol = ''
format = '[\[$symbol$maybe_int\]]($style) '
not_executable_symbol = "[!EXE](red)"
style = 'purple'
not_found_symbol = "[!FOUND](red)"
sigint_symbol = "[SIGINT](red)"
signal_symbol = "[SIG](red)"
map_symbol = true
pipestatus = true
pipestatus_format = '$pipestatus=> [\[$common_meaning$signal_name$maybe_int\]]($style) '
disabled = false

[time]
disabled = false
format = '\[[$time]($style)\]'

[username]
show_always = true
format = "[$user]($style)"

