[window]
padding = { x = 7, y = 5 }
dynamic_padding = true
dynamic_title = false

[font]
normal = { family = "Iosevka Term", style = "Regular" }
bold = { family = "Iosevka Term", style = "Bold" }
italic = { family = "Iosevka Term", style = "Italic" }
bold_italic = { family = "Iosevka Term", style = "Bold Italic" }
size = 14

[colors.primary]
background = "#111111"
foreground = "#c1c9d2"

[colors.cursor]
text = "#111111"
cursor = "#c1c9d2"

[colors.selection]
text = "#ffffff"
background = "#3e4043"

[colors.normal]
black = "#000000"
red = "#ed5f74"
green = "#1ea672"
yellow = "#d97917"
blue = "#688ef1"
magenta = "#c96ed0"
cyan = "#3a97d4"
white = "#e3e8ee"

[colors.bright]
black = "#697386"
red = "#fbb5b2"
green = "#85d996"
yellow = "#efc078"
blue = "#9fcdff"
magenta = "#f0b4e4"
cyan = "#7fd3ed"
white = "#ffffff"

[cursor]
style = { shape = "Underline", blinking = "On" }

[selection]
save_to_clipboard = true
