[language-server.harper-ls]
command = "harper-ls"
args = ["--stdio"]
config = { harper-ls = { diagnosticSeverity = "error", linters = { long_sentences = false } } }

[language-server.wakatime]
command = "wakatime-ls"

[language-server.yaml-language-server.config.yaml]
format = { enable = true }
validation = true
schemaStore = { enable = true }

[language-server.yaml-language-server.config.yaml.schemas]
"https://json.schemastore.org/github-workflow.json" = ".github/workflows/*.{yml,yaml}"
"https://raw.githubusercontent.com/ansible-community/schemas/main/f/ansible-tasks.json" = "roles/{tasks,handlers}/*.{yml,yaml}"
"https://raw.githubusercontent.com/redhat-developer/vscode-tekton/refs/heads/main/scheme/tekton.dev/v1beta1_Task.json" = "tasks/*.{yml,yaml}"
"https://raw.githubusercontent.com/redhat-developer/vscode-tekton/refs/heads/main/scheme/tekton.dev/v1_Pipeline.json" = "pipelines/*.{yml,yaml}"
"https://raw.githubusercontent.com/redhat-developer/vscode-tekton/refs/heads/main/scheme/tekton.dev/v1_PipelineRun.json" = ".tekton/*.{yml,yaml}"

[[language]]
name = "c"
file-types = ["c", "h"]
formatter = { command = 'clang-format' }
auto-format = false
language-servers = ["clangd", "wakatime"]
indent = { tab-width = 4, unit = "    " }

[[language]]
name = "cpp"
file-types = ["cpp", "cc", "cxx", "hpp", "hcc", "hxx"]
formatter = { command = 'clang-format' }
language-servers = ["clangd", "wakatime"]
auto-format = false
indent = { tab-width = 4, unit = "    " }

[[language]]
name = "markdown"
file-types = ["md", "rst", "adoc"]
language-servers = ["marksman", "wakatime", "harper-ls"]

[[language]]
name = "go"
language-servers = ["gopls", "wakatime"]
formatter = { command = 'goimports' }
auto-format = true

[[language]]
name = "yaml"
language-servers = ["yaml-language-server", "wakatime"]

[[language]]
name = "bash"
language-servers = ["bash-language-server", "wakatime"]

[[language]]
name = "python"
language-servers = ["pylsp", "wakatime"]
auto-format = true

[[language]]
name = "rust"
language-servers = ["rust-analyzer", "wakatime"]
auto-format = true

[[language]]
name = "typescript"
language-servers = ["typescript-language-server", "wakatime"]
auto-format = true

[[language]]
name = "javascript"
language-servers = ["typescript-language-server", "wakatime"]
auto-format = true

[[language]]
name = "html"
language-servers = ["vscode-html-language-server", "wakatime"]

[[language]]
name = "css"
language-servers = ["vscode-css-language-server", "wakatime"]

[[language]]
name = "lua"
language-servers = ["lua-language-server", "wakatime"]

[[language]]
name = "dockerfile"
language-servers = ["docker-langserver", "wakatime"]

[[language]]
name = "json"
language-servers = ["vscode-json-language-server", "wakatime"]

[[language]]
name = "toml"
language-servers = ["taplo", "wakatime"]
